# compile-sketches.yml
#
# This is a GitHub workflow file, written in YAML that checks if
# sketches within the repo compile correctly.
# 
# A minimal GitHub workflow is composed of three main parts
#     - A name (name:)
#     - Conditions when the workflow is activated (on:)
#     - The tasks that the workflow must do (jobs)
# 
# This workflow is called `Compile Sketches`. If you click on the
# `Actions` tab while browsing the repo, you can see if listed on the
# left panel.
# 
# There are two ways this workflow can be automatically triggered. Either by
# Pushing to the main branch, or making a PR to the main branch.
# Alternatively, it is possible to manually trigger this workflow by
# going to the Action tab, selecting Compile Sketches and clicking
# `Run workflow`.
#
# This workflow has only one job called `compile-sketch` which runs
# on the latest ubuntu runner provided by GitHub. The Checkout action
# provided by GitHub is used to load the repo to the runner. Afterwards,
# the compile-sketches GitHub action developed by Arduino is run.
#
# This workflow is set to compile for the Uno board. And it also loads the
# latest version of the Servo library as well as version 1.1.3 of the
# Stepper motor library
#
# This .yml can form an example to develop CI workflows for your own libraries and sketches.
# To see the features supported by the arduino/compile-sketches action, visit:
# https://github.com/marketplace/actions/compile-arduino-sketches
#
#
# Created 28th August 2023
# By Ali Jahangiri
#
# https://github.com/aliphys/ArduinoBasicCompileSketch/blob/main/.github/workflows/compile-sketches.yml
#


# You will see this name in the Actions tab on GitHub
name: Compile Sketches

# Specify conditions for workflow to run
on:
  push: # push to main branch
    branches:
      -main
  
  pull_request: # PR to main branch
    branches:
      -main

  workflow_dispatch: # Manually via button in the Actions tab


# This workflow involves only one job to do, called compile-sketch
jobs:
  compile-sketch:
    runs-on: ubuntu-latest # runner is latest Github-hosted Ubuntu
    steps: # define what steps should be taken
      # GA for checking out repo to runner -> https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # GA for compiling sketches -> https://github.com/arduino/compile-sketches
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno" # specify fully qualified board name to compile sketches for
          libraries: |
            # load latest version of Servo library from arduino-libraries org
            - name: Servo
            # load version 1.1.3 of Stepper library 
            - name: Stepper # 
              version: 1.1.3
